name: TUI Booking Automation CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Run linting
      run: npm run lint
      
    - name: Run type checking
      run: npx tsc --noEmit
      
    - name: Run Playwright tests
      run: npm test
      
    - name: Generate Allure report
      if: always()
      run: |
        echo "Generating Allure report..."
        npm run allure:generate || echo "Allure report generation failed, but continuing..."
        echo "Checking if allure-report directory exists:"
        ls -la allure-report/ || echo "allure-report directory not found"
      
    - name: Upload Playwright report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30
        
    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results-${{ matrix.node-version }}
        path: allure-results/
        retention-days: 30
        
    - name: Upload Allure report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report-${{ matrix.node-version }}
        path: allure-report/
        retention-days: 30
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.node-version }}
        path: test-results/
        retention-days: 30

  # Deploy Allure report to GitHub Pages (optional)
  deploy-report:
    if: always() && github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Download Allure report artifact
      uses: actions/download-artifact@v4
      with:
        name: allure-report-18.x
        path: allure-report/
        
    - name: List downloaded files
      run: |
        echo "Contents of allure-report directory:"
        ls -la allure-report/ || echo "Directory not found"
        echo "Checking if index.html exists:"
        ls -la allure-report/index.html || echo "index.html not found"
        
    - name: Create fallback report if needed
      if: always()
      run: |
        if [ ! -f "allure-report/index.html" ]; then
          echo "Creating fallback report..."
          mkdir -p allure-report
          cat > allure-report/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>Test Report - Fallback</title>
            <style>
                body { font-family: Arial, sans-serif; margin: 40px; }
                .header { background: #f0f0f0; padding: 20px; border-radius: 5px; }
                .info { margin: 20px 0; }
            </style>
        </head>
        <body>
            <div class="header">
                <h1>🧪 Test Report</h1>
                <p>Allure report generation failed, but tests were executed.</p>
            </div>
            <div class="info">
                <p><strong>Status:</strong> Tests executed but Allure report generation failed</p>
                <p><strong>Time:</strong> $(date)</p>
                <p><strong>Commit:</strong> ${{ github.sha }}</p>
            </div>
        </body>
        </html>
        EOF
          echo "Fallback report created"
        fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload to Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: allure-report/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4